events {
    worker_connections 1024;
}

http {
    upstream backend_servers {
        # Round-robin by default
        server app1:3001;
        server app2:3002;
    }

    server {
        listen 80;

        # Increase max upload size in NGINX to match application limits
        client_max_body_size 5M;

        location / {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
